// 작업 로그 공통 코드. 값·표시명은 공통 코드 정의서 그대로 (PLAN 4장).
// 자동 예약은 RESERVATION_CREATED + 주체 SYSTEM, 불합격은 INSPECTION_REGISTERED의 판정 결과로 구분한다.

export const ACTOR_TYPE = {
  USER: 'USER',
  SYSTEM: 'SYSTEM',
} as const;
export type ActorType = (typeof ACTOR_TYPE)[keyof typeof ACTOR_TYPE];
export const ACTOR_TYPE_LABEL: Record<ActorType, string> = {
  USER: '사용자',
  SYSTEM: '시스템',
};

/** 확정 29개 (REQ-LOG-002와 1:1) */
export const BUSINESS_EVENT_TYPE = {
  SALES_ORDER_CREATED: 'SALES_ORDER_CREATED',
  SALES_ORDER_CANCELLED: 'SALES_ORDER_CANCELLED',
  PRODUCTION_PLAN_CREATED: 'PRODUCTION_PLAN_CREATED',
  PRODUCTION_PLAN_CANCELLED: 'PRODUCTION_PLAN_CANCELLED',
  REPRODUCTION_PLAN_CREATED: 'REPRODUCTION_PLAN_CREATED',
  SURPLUS_CONVERTED: 'SURPLUS_CONVERTED',
  PRODUCTION_STARTED: 'PRODUCTION_STARTED',
  PRODUCTION_RESULT_REGISTERED: 'PRODUCTION_RESULT_REGISTERED',
  INSPECTION_REGISTERED: 'INSPECTION_REGISTERED',
  DISPOSITION_SET: 'DISPOSITION_SET',
  RESERVATION_CREATED: 'RESERVATION_CREATED',
  RESERVATION_CONVERTED: 'RESERVATION_CONVERTED',
  RESERVATION_RELEASED: 'RESERVATION_RELEASED',
  ALLOCATION_RECOMMENDED: 'ALLOCATION_RECOMMENDED',
  ALLOCATION_CONFIRMED: 'ALLOCATION_CONFIRMED',
  ALLOCATION_CHANGED: 'ALLOCATION_CHANGED',
  ALLOCATION_RELEASED: 'ALLOCATION_RELEASED',
  PURCHASE_REQUISITION_CREATED: 'PURCHASE_REQUISITION_CREATED',
  PURCHASE_REQUISITION_APPROVED: 'PURCHASE_REQUISITION_APPROVED',
  PURCHASE_REQUISITION_REJECTED: 'PURCHASE_REQUISITION_REJECTED',
  PURCHASE_ORDER_CREATED: 'PURCHASE_ORDER_CREATED',
  GOODS_RECEIPT_CONFIRMED: 'GOODS_RECEIPT_CONFIRMED',
  SHIPMENT_REQUEST_CREATED: 'SHIPMENT_REQUEST_CREATED',
  GOODS_ISSUE_CONFIRMED: 'GOODS_ISSUE_CONFIRMED',
  MILL_SHEET_ISSUED: 'MILL_SHEET_ISSUED',
  DRAFT_CREATED: 'DRAFT_CREATED',
  DRAFT_CONFIRMED: 'DRAFT_CONFIRMED',
  DRAFT_REJECTED: 'DRAFT_REJECTED',
  DRAFT_EXECUTED: 'DRAFT_EXECUTED',
} as const;
export type BusinessEventType = (typeof BUSINESS_EVENT_TYPE)[keyof typeof BUSINESS_EVENT_TYPE];
export const BUSINESS_EVENT_TYPE_LABEL: Record<BusinessEventType, string> = {
  SALES_ORDER_CREATED: '수주 등록',
  SALES_ORDER_CANCELLED: '수주 취소',
  PRODUCTION_PLAN_CREATED: '생산계획 생성',
  PRODUCTION_PLAN_CANCELLED: '생산계획 취소',
  REPRODUCTION_PLAN_CREATED: '재생산 계획 생성',
  SURPLUS_CONVERTED: '여재 전환',
  PRODUCTION_STARTED: '작업 시작',
  PRODUCTION_RESULT_REGISTERED: '실적 등록(작업 완료)',
  INSPECTION_REGISTERED: '검사 등록·판정',
  DISPOSITION_SET: '불합격 처리 상태 지정',
  RESERVATION_CREATED: '예약',
  RESERVATION_CONVERTED: '예약 전환',
  RESERVATION_RELEASED: '예약 해제',
  ALLOCATION_RECOMMENDED: '배정 추천',
  ALLOCATION_CONFIRMED: '배정 확정',
  ALLOCATION_CHANGED: '배정 변경',
  ALLOCATION_RELEASED: '배정 해제',
  PURCHASE_REQUISITION_CREATED: '구매요청 등록',
  PURCHASE_REQUISITION_APPROVED: '구매요청 승인',
  PURCHASE_REQUISITION_REJECTED: '구매요청 반려',
  PURCHASE_ORDER_CREATED: '발주',
  GOODS_RECEIPT_CONFIRMED: '입고 확정',
  SHIPMENT_REQUEST_CREATED: '출하요청 등록',
  GOODS_ISSUE_CONFIRMED: '출고 확정',
  MILL_SHEET_ISSUED: '밀시트 발행',
  DRAFT_CREATED: '초안 생성',
  DRAFT_CONFIRMED: '초안 확정',
  DRAFT_REJECTED: '초안 반려',
  DRAFT_EXECUTED: '초안 실행(ERP 반영)',
};

export const BUSINESS_EVENT_AREAS = ['수주', '생산', '품질', '재고', '구매', '출하', '초안'] as const;
export type BusinessEventArea = (typeof BUSINESS_EVENT_AREAS)[number];
export const BUSINESS_EVENT_AREA: Record<BusinessEventType, BusinessEventArea> = {
  SALES_ORDER_CREATED: '수주',
  SALES_ORDER_CANCELLED: '수주',
  PRODUCTION_PLAN_CREATED: '생산',
  PRODUCTION_PLAN_CANCELLED: '생산',
  REPRODUCTION_PLAN_CREATED: '생산',
  SURPLUS_CONVERTED: '생산',
  PRODUCTION_STARTED: '생산',
  PRODUCTION_RESULT_REGISTERED: '생산',
  INSPECTION_REGISTERED: '품질',
  DISPOSITION_SET: '품질',
  RESERVATION_CREATED: '재고',
  RESERVATION_CONVERTED: '재고',
  RESERVATION_RELEASED: '재고',
  ALLOCATION_RECOMMENDED: '재고',
  ALLOCATION_CONFIRMED: '재고',
  ALLOCATION_CHANGED: '재고',
  ALLOCATION_RELEASED: '재고',
  PURCHASE_REQUISITION_CREATED: '구매',
  PURCHASE_REQUISITION_APPROVED: '구매',
  PURCHASE_REQUISITION_REJECTED: '구매',
  PURCHASE_ORDER_CREATED: '구매',
  GOODS_RECEIPT_CONFIRMED: '구매',
  SHIPMENT_REQUEST_CREATED: '출하',
  GOODS_ISSUE_CONFIRMED: '출하',
  MILL_SHEET_ISSUED: '출하',
  DRAFT_CREATED: '초안',
  DRAFT_CONFIRMED: '초안',
  DRAFT_REJECTED: '초안',
  DRAFT_EXECUTED: '초안',
};

/**
 * 🟡 제안 값 (공통 코드 정의서 3장). 해당 기능(P2·EX)을 구현할 때 위 확정 표로 옮긴다.
 * 지금은 '준비 중' 화면의 표시에만 쓰고, 작업 로그 기록에는 쓰지 않는다.
 */
export const PROPOSED_BUSINESS_EVENT_TYPE = {
  AGENT_RISK_DETECTED: 'AGENT_RISK_DETECTED',
  CASE_REGISTERED: 'CASE_REGISTERED',
} as const;
export type ProposedBusinessEventType = (typeof PROPOSED_BUSINESS_EVENT_TYPE)[keyof typeof PROPOSED_BUSINESS_EVENT_TYPE];
export const PROPOSED_BUSINESS_EVENT_TYPE_LABEL: Record<ProposedBusinessEventType, string> = {
  AGENT_RISK_DETECTED: 'Agent 위험 감지',
  CASE_REGISTERED: '과거 사례 등록',
};
export const PROPOSED_BUSINESS_EVENT_TYPE_GRADE: Record<ProposedBusinessEventType, 'P2' | 'EX'> = {
  AGENT_RISK_DETECTED: 'P2',
  CASE_REGISTERED: 'EX',
};

/**
 * 작업 로그 사유 코드. 공통 코드 그룹이 아니다(EVENT_REASON_CODE 그룹은 없앴다, PLAN 4장).
 * 업무 프로세스 9.3의 제안 8개만 쓴다 (ERD business_event.reason_code). 표시명은 문서에 없어 두지 않는다.
 */
export const EVENT_REASON_CODES = [
  'STOCK_FIRST',
  'FIFO_RECOMMENDATION',
  'ORDER_SHORTAGE',
  'ORDER_CANCELLED',
  'QUALITY_FAILURE',
  'SURPLUS_CONVERSION',
  'ALLOCATION_CHANGE',
  'DRAFT_CONFIRMED',
] as const;
export type EventReasonCode = (typeof EVENT_REASON_CODES)[number];
export const isEventReasonCode = (value: string): value is EventReasonCode =>
  (EVENT_REASON_CODES as readonly string[]).includes(value);
